### ISSUE TITLE
Add Relation Management

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-dynamic-search#100]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

```yaml
dynamic_search:
    context:
        default:

            relation_management:
                -
                    class: Car
                    relations:
                        -
                            name: parts 
                            options: []
```

This will add an Eventlistener to the `Car` Object (preUpdate) which adds all relations (Only the configured ones from `dynamic_search.context.[...CONTEXT].data_provider.options.always`) from the given property `parts` to the DS queue (Within the postUpdate event!)
