### ISSUE TITLE
Multiple data providers feeding an index provider

### ISSUE THREAD

**Issue by gadget60** [dachcom-digital/pimcore-dynamic-search#16]
Not sure if I'm wrong, but wouldn't it make sense so have multiple data providers feed a single index provider? Like, having static pages indexed using web crawler, but product/event/whatever detail page indexed via Objects? 
Looking at the configuration file I don't think this is possible: Every context expects a single data_provider child node. Maybe I missed something...?

**Comment by solverat** [comment]
@gadget60 I'm afraid that's not possible. 
But you could define two context definitions:

```yaml

dynamic_search:
    enable_pimcore_element_listener: true
    context:
        crawler: # crawler context
            index_provider:
                service: 'lucene'
                options:
                    database_name: 'cms'
            data_provider:
                service: 'web_crawler'
                options:
                    always:
                        own_host_only: true
                    full_dispatch:
                        seed: 'http://your-domain.test'
                        valid_links:
                            - '@^http://your-domain.test.*@i'
                        user_invalid_links:
                            - '@^http://your-domain.test\/products.*@i' # do not track products in this context
                    single_dispatch:
                        host: 'http://your-domain.test.test'
                normalizer:
                    service: 'web_crawler_localized_resource_normalizer'
            output_channels:
                suggestions:
                    service: 'lucene_suggestions'
                    normalizer:
                        service: 'lucene_document_key_value_uri_normalizer'
                        options:
                            skip_fields:
                                - 'id'
                                - 'locale'
                                - 'text'
                search:
                    service: 'lucene_search'
                    use_frontend_controller: true
                    normalizer:
                        service: 'lucene_document_key_value_uri_normalizer'
                    options:
                        phrased_search: true
                        fuzzy_search: true
                    paginator:
                        enabled: true
                        max_per_page: 10

        trinity:  # trinity context
            index_provider:
                service: 'lucene'
                options:
                    database_name: 'products'
            data_provider:
                service: 'trinity_data'
                normalizer:
                    service: 'trinity_localized_resource_normalizer'
                    options:
                        locales:
                            - de
                            - en
                options:
                    always:
                        index_asset: false
                        index_document: false
                        index_object: true # only track objects of type "Product"
                        object_class_names:
                            - Product
            output_channels:
                suggestions:
                    service: 'lucene_suggestions'
                    normalizer:
                        service: 'lucene_document_key_value_uri_normalizer'
                        options:
                            skip_fields:
                                - 'id'
                                - 'locale'
                                - 'text'
                search:
                    service: 'lucene_search'
                    use_frontend_controller: true
                    normalizer:
                        service: 'lucene_document_key_value_uri_normalizer'
                    options:
                        phrased_search: true
                        fuzzy_search: true
                    paginator:
                        enabled: true
                        max_per_page: 10

```

Then fetch results by using those context urls:

- https://domain.com/dynamic-search/crawler/search?q=cms-query
- https://domain.com/dynamic-search/trinity/search?q=product-query

The only downside with this solution: You're not able to query data globally.

To give you a recommendation from my side: Try to avoid using the crawler data provider. Trinity is 1000x times faster and allows you to do to configure index data in a much more accurate way!
