### ISSUE TITLE
Provide Inherited Object/Variant Data

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-dynamic-search#42]
| Q                | A
| ---------------- | -----
| Branch          | master
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

- Create Object
- Create Variant for Object
- Dispatch Queue
  - Index contains object and variant
- Change Object property
- Dispatch Queue
  - Variant in index is untouched

While technical correct (we only add objects to queue by pimcores post-update event) we should think about a proper solution for this.

Introduce a new configuration flag for the trinity data provider `object_enable_inheritance`. If `true`, load all sub-elements and add them to the queue too. 

```yaml
dynamic_search:
    context:
        default:
            data_provider:
                service: 'trinity_data'
                options:
                    always:
                        index_object: true
                        object_enable_inheritance: true
```
