### ISSUE TITLE
Allow different Layouts (List, Ajax) in Output Channel

### ISSUE THREAD

**Issue by pascalmoser** [dachcom-digital/pimcore-dynamic-search#8]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | no

**Comment by solverat** [comment]
Definition:

Default: `null` (resolves `List` in searchAction and `MultiList` in multiSearch if not defined in options).

```yml
search:
    service: 'lucene_search'
    internal: false
    use_frontend_controller: true
    view_name: 'MyView' # only works, if use_frontend_controller === true
```
